### ISSUE TITLE
setup procedure 

### ISSUE THREAD

**Issue by isathish** [Sinclert/SentimentAI#2]
Please help me the guideline for setup the system

**Comment by Sinclert** [comment]
I will write down the basic steps to make the project work:

1. Install Python 3 (version 3.4 or superior). You can do it from this page: https://www.python.org
2. Install 'pip' (Python packages manager). You can do it from this page: https://pip.pypa.io/en/stable/installing/
3. Install the packages specified in the 'Requirements' section of the README file executing the following command line:
```
pip3 install <name of the package in lowercase>
```
For example:
```
pip3 install scikit-learn
```

With those steps you will be able to train any ML model you would like. If you additionally want to perform classification over certain tweets, or increase your datasets by using Twitter Search API, you will need to do the following:

4. Create a Twitter App in in order to obtain the required keys. You will need to log in with you Twitter account in this page: https://apps.twitter.com , and then create an app.
5. Fulfill the mandatory fields as you wish.
6. After been created, jump into the 'Keys and Access Tokens' section, and copy the following 4 keys: <i>Consumer Key</i>, <i>Consumer Secret</i>, <i>Access token</i> and <i>Access Token Secret</i>.
7. Finally, paste those values into the proper fields in the <i>twitter_keys.py</i> file, inside the <i>src</i> folder.
