### ISSUE TITLE
error: the following arguments are required: mode

### ISSUE THREAD

**Issue by isathish** [Sinclert/SentimentAI#3]
`kmb01:src sathish$ python3  main.py
usage: main.py [mode] [arguments]
main.py: error: the following arguments are required: mode
kmb01:src sathish$ `

**Comment by Sinclert** [comment]
I have updated the README to clarify the possible modes of execution.

That error appears because you have not specified one of the possible execution modes, which are:
A ) <i>train_model</i>
B) <i>search_data</i>
C) <i>predict_user</i>
D) <i>predict_stream</i>

**Depending on the mode that you select, the following arguments change**. If you want to know more about this, there is a whole section called "Usage" in the README, in which the different modes of execution, with their particular parameters are explained.
